version: 2

python:
    version: 3.7
    install:
        - requirements: docs/requirements.txt
        - method: setuptools
          path: .
        system_packages: true

sphinx:
    builder: html
    configuration: docs/conf.py
formats: all
