version: 2

formats:
    all

python:
   version: 3.7
   install:
      - requirements: docs/requirements.txt
    system_packages: true

sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: true
